name: Gym Injury MLOps Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install fastapi uvicorn scikit-learn joblib numpy pandas pytest httpx

      - name: Train model
        run: python model/train_model.py

      - name: Run tests
        run: pytest tests/ -v
